# crypto-config-nexon.yaml
PeerOrgs:
  - Name: Nexon
    Domain: nexon.example.com
    EnableNodeOUs: true
    Template:
      Count: 3
      SANS:
        - "127.0.0.1"
        - localhost
    Users:
      Count: 1