# crypto-config-ncsoft.yaml
PeerOrgs:
  - Name: NCsoft
    Domain: ncsoft.example.com
    EnableNodeOUs: true
    Template:
      Count: 3
      SANS:
        - "127.0.0.1"
        - localhost
    Users:
      Count: 1